services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Visol\Ipauthtrigger\:
    resource: '../Classes/*'

  Visol\Ipauthtrigger\Service\AuthenticationService:
    public: true
